### ISSUE TITLE
confused on line 32 35 37

### ISSUE THREAD

**Issue by AsadullahFarooqi** [candyer/leetcode#1]
can you please explain the 32, 35 and 37 line logic i mean the **pre** variable logic what is the role of that variable. please

**Comment by candyer** [comment]
Hello, which file were you talking about?

**Comment by AsadullahFarooqi** [comment]
My apologies for late reply (Sorry)
and i am talking about this https://github.com/candyer/leetcode/blob/master/lastSubstring.py file
I think it is for the consecutive characters, to boost the speed, am i right?

**Comment by candyer** [comment]
Yes, you are right 👍 :)

- on line 32: the variable pre's default value could be any integer <= -2;
- on line 35: if there are blocks of the biggest character (max(s)), only the first one in each block matters, (e.g. 'zzzzzazzzz',  only use max function on index 0 and 6). But this is a small optimization for the brute force solution, doesn't change the final time complexity;
- on line 37: save the new index of the visited biggest character (max(s)).

Here is the simpler version of the brute force solution, I removed some unnecessary lines.
```
def lastSubstring(s):
	maxi = max(s)
	pre = -2
	res = ''
	for i in range(len(s)):
		if s[i] == maxi:
			if pre + 1 != i:
				res = max(res, s[i:])
			pre = i
	return res
```


And below is a better solution by using 'Suffix Arrays'
```
def lastSubstring(s):
	if len(set(s)) == 1:
		return s
	n = len(s)
	pos = n - 1
	for i in range(n - 2, -1, -1):
		j = 0
		while pos + j < n:
			curr, tail = s[i + j], s[pos + j]
			if curr < tail:
				break
			elif curr > tail:
				pos = i
				break
			else:
				j += 1
		if pos + j == n:
			pos = i
	return s[pos:]
```

**Comment by AsadullahFarooqi** [comment]
Thanks man i really appreciate that. Your code is very good, I would like code with  you i wanna learn. will you be okay if we code together on weekend or anytime you free?
i mean solve problems together! Please
if there is anyway it can be possible please let me know it means a lot to me.

**Comment by candyer** [comment]
Sorry for my late reply. Thank you a lot for giving me so much credit. I'm afraid coding together would be a bit difficult due to the time difference, but I will keep uploading my solutions and we can discuss here :)

**Comment by AsadullahFarooqi** [comment]
My apologies for late reply. I couldn’t get in for past few days because of a death in my family.
I really appreciate your response. Thanks a lot. We can try at least how does it goes, What do you say? If it wasn’t working then we will stop.

**Comment by AsadullahFarooqi** [comment]
can i have your email or linkedin or something?
